server:
  port: 8888
spring:
  application:
    name: mayikt-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: my-member
          uri: lb://mayikt-member
          predicates:
            - Path=/mayikt-member/**
        - id: mayikt
          uri: http://www.mayikt.com
          predicates:
            - Path=/mayikt/**